"""Type stubs for the exteraGram SDK module ``android_utils``."""

from collections.abc import Callable
from typing import Any

class R:
    def __init__(self, fn: Callable[[], Any]) -> None: ...
    def run(self) -> Any: ...

class OnClickListener:
    def __init__(self, fn: Callable[[Any], Any]) -> None: ...
    def onClick(self, view: Any = ...) -> Any: ...

class OnLongClickListener:
    def __init__(self, fn: Callable[[Any], bool]) -> None: ...
    def onLongClick(self, view: Any = ...) -> bool: ...

def log(data: Any) -> None: ...
def run_on_ui_thread(callback: Callable[[], Any], delay: int = ...) -> None: ...
def copy_to_clipboard(text: str) -> None: ...
