"""Type stubs for the exteraGram SDK module ``base_plugin``.

Shipped by catalib for IDE autocomplete and type checking. Not importable
on the dev machine; installed into a project's ``typings/`` by
``catalib stubs``. Signatures mirror the official SDK surface.
"""

from collections.abc import Callable
from typing import Any

class HookStrategy:
    DEFAULT: str
    CANCEL: str
    MODIFY: str
    MODIFY_FINAL: str

class HookResult:
    strategy: str
    params: Any
    request: Any
    response: Any
    update: Any
    updates: Any
    def __init__(
        self,
        strategy: str | None = ...,
        params: Any = ...,
        request: Any = ...,
        response: Any = ...,
        update: Any = ...,
        updates: Any = ...,
    ) -> None: ...

class MenuItemType:
    DRAWER_MENU: str
    MESSAGE_CONTEXT_MENU: str
    CHAT_ACTION_MENU: str
    PROFILE_ACTION_MENU: str

class MenuItemData:
    def __init__(
        self,
        menu_type: str,
        text: str,
        on_click: Callable[[dict[str, Any]], Any],
        *,
        icon: str = ...,
        subtext: str = ...,
        item_id: str = ...,
        condition: Callable[[dict[str, Any]], bool] | None = ...,
        priority: int = ...,
    ) -> None: ...

class AppEvent:
    START: Any
    STOP: Any
    PAUSE: Any
    RESUME: Any

class HookFilter:
    RESULT_IS_NULL: Any
    RESULT_IS_TRUE: Any
    RESULT_IS_FALSE: Any
    RESULT_NOT_NULL: Any
    @staticmethod
    def ResultIsInstanceOf(clazz: Any) -> Any: ...
    @staticmethod
    def ResultEqual(value: Any) -> Any: ...
    @staticmethod
    def ResultNotEqual(value: Any) -> Any: ...
    @staticmethod
    def ArgumentIsNull(index: int) -> Any: ...
    @staticmethod
    def ArgumentNotNull(index: int) -> Any: ...
    @staticmethod
    def ArgumentIsFalse(index: int) -> Any: ...
    @staticmethod
    def ArgumentIsTrue(index: int) -> Any: ...
    @staticmethod
    def ArgumentIsInstanceOf(index: int, clazz: Any) -> Any: ...
    @staticmethod
    def ArgumentEqual(index: int, value: Any) -> Any: ...
    @staticmethod
    def ArgumentNotEqual(index: int, value: Any) -> Any: ...
    @staticmethod
    def Condition(mvel_expr: str, obj: Any = ...) -> Any: ...
    @staticmethod
    def Or(*filters: Any) -> Any: ...

def hook_filters(*filters: Any) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...

class BaseHook: ...
class MethodHook(BaseHook): ...
class MethodReplacement(BaseHook): ...

class BasePlugin:
    def on_plugin_load(self) -> None: ...
    def on_plugin_unload(self) -> None: ...
    def create_settings(self) -> list[Any]: ...
    def add_on_send_message_hook(self, priority: int = ...) -> None: ...
    def add_hook(self, name: str, match_substring: bool = ..., priority: int = ...) -> None: ...
    def hook_method(
        self,
        method: Any,
        before: Callable[[Any], Any] | None = ...,
        after: Callable[[Any], Any] | None = ...,
        replace: Callable[[Any], Any] | None = ...,
        before_filters: list[Any] | None = ...,
        after_filters: list[Any] | None = ...,
        priority: int = ...,
    ) -> Any: ...
    def hook_all_methods(
        self, clazz: Any, method_name: str, handler: Callable[[Any], Any]
    ) -> list[Any]: ...
    def hook_all_constructors(self, clazz: Any, handler: Callable[[Any], Any]) -> list[Any]: ...
    def unhook_method(self, handle: Any) -> None: ...
    def add_menu_item(self, data: MenuItemData) -> Any: ...
    def remove_menu_item(self, item_id: Any) -> None: ...
    def get_setting(self, key: str, default: Any = ...) -> Any: ...
    def set_setting(self, key: str, value: Any, reload_settings: bool = ...) -> None: ...
    def export_settings(self) -> dict[str, Any]: ...
    def import_settings(self, data: dict[str, Any]) -> None: ...
    def log(self, message: Any) -> None: ...
    # Реализуются плагином (необязательны):
    def on_send_message_hook(self, account: int, params: Any) -> HookResult: ...
    def pre_request_hook(self, request_name: str, account: int, request: Any) -> Any: ...
    def post_request_hook(
        self, request_name: str, account: int, response: Any, error: Any
    ) -> Any: ...
    def on_update_hook(self, update_name: str, account: int, update: Any) -> Any: ...
    def on_updates_hook(self, container_name: str, account: int, updates: Any) -> Any: ...
    def on_app_event(self, event_type: Any) -> None: ...
    def before_hooked_method(self, param: Any) -> Any: ...
    def after_hooked_method(self, param: Any) -> Any: ...
    def replace_hooked_method(self, param: Any) -> Any: ...

def find_class(name: str) -> Any | None: ...
