"""Type stubs for the exteraGram SDK module ``file_utils``."""

def get_plugins_dir() -> str: ...
def get_cache_dir() -> str: ...
def get_files_dir() -> str: ...
def get_images_dir() -> str: ...
def get_videos_dir() -> str: ...
def get_audios_dir() -> str: ...
def get_documents_dir() -> str: ...
def ensure_dir_exists(path: str) -> None: ...
def list_dir(
    path: str,
    recursive: bool = ...,
    extensions: list[str] | None = ...,
) -> list[str]: ...
def write_file(path: str, content: str) -> None: ...
def read_file(path: str) -> str | None: ...
def delete_file(path: str) -> bool: ...
