"""Type stubs for the exteraGram SDK module ``hook_utils``."""

from typing import Any

def find_class(name: str) -> Any | None: ...
def get_private_field(obj: Any, field_name: str) -> Any: ...
def set_private_field(obj: Any, field_name: str, new_value: Any) -> bool: ...
def get_static_private_field(clazz: Any, field_name: str) -> Any: ...
def set_static_private_field(clazz: Any, field_name: str, new_value: Any) -> bool: ...
