"""Type stubs for the exteraGram SDK module ``ui.alert``."""

from collections.abc import Callable
from typing import Any

class AlertDialogBuilder:
    ALERT_TYPE_MESSAGE: int
    ALERT_TYPE_LOADING: int
    ALERT_TYPE_SPINNER: int
    BUTTON_POSITIVE: int
    BUTTON_NEGATIVE: int
    def __init__(
        self,
        context: Any,
        progress_style: int = ...,
        resources_provider: Any = ...,
    ) -> None: ...
    def set_title(self, title: str) -> AlertDialogBuilder: ...
    def set_message(self, message: str) -> AlertDialogBuilder: ...
    def set_view(self, view: Any, height: int = ...) -> AlertDialogBuilder: ...
    def set_items(
        self, items: list[str], listener: Any = ..., icons: Any = ...
    ) -> AlertDialogBuilder: ...
    def set_positive_button(
        self, text: str, listener: Callable[[Any, int], Any] | None = ...
    ) -> AlertDialogBuilder: ...
    def set_negative_button(
        self, text: str, listener: Callable[[Any, int], Any] | None = ...
    ) -> AlertDialogBuilder: ...
    def set_neutral_button(
        self, text: str, listener: Callable[[Any, int], Any] | None = ...
    ) -> AlertDialogBuilder: ...
    def make_button_red(self, button_type: int) -> AlertDialogBuilder: ...
    def set_on_dismiss_listener(self, listener: Any = ...) -> AlertDialogBuilder: ...
    def set_on_cancel_listener(self, listener: Any = ...) -> AlertDialogBuilder: ...
    def set_dim_enabled(self, enabled: bool) -> AlertDialogBuilder: ...
    def set_blurred_background(
        self, blur: bool, blur_behind_if_possible: bool = ...
    ) -> AlertDialogBuilder: ...
    def set_progress(self, progress: int) -> AlertDialogBuilder: ...
    def create(self) -> Any: ...
    def show(self) -> Any: ...
    def dismiss(self) -> None: ...
