"""Type stubs for the exteraGram SDK module ``extera_utils.classes`` (class proxy)."""

from collections.abc import Callable
from typing import Any

class Base: ...
class PyObj: ...
class J: ...

class ClassProxy:
    @staticmethod
    def from_java(java_obj: Any) -> Any: ...

def java_subclass(*bases: Any, **kwargs: Any) -> Callable[[type], type]: ...
def joverride(java_method_name: str | None = ...) -> Callable[[Callable[..., Any]], Any]: ...
def joverload(
    java_method_name: str, arg_types: list[Any]
) -> Callable[[Callable[..., Any]], Any]: ...
def jmethod(*args: Any, **kwargs: Any) -> Any: ...
def jconstructor(arg_types: list[Any]) -> Callable[[Callable[..., Any]], Any]: ...
def jpreconstructor(arg_types: list[Any]) -> Callable[[Callable[..., Any]], Any]: ...
def jclassbuilder(*args: Any, **kwargs: Any) -> Any: ...
def jMVELmethod(*args: Any, **kwargs: Any) -> Any: ...
def jMVELoverride(*args: Any, **kwargs: Any) -> Any: ...
def jgetmethod(java_method_name: str) -> Any: ...
def jsetmethod(java_method_name: str) -> Any: ...
